steps:
 # Deploy the function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - --runtime=nodejs10
      - --trigger-http
      - --region=northamerica-northeast1
      - --memory=128
      - --source=./  # Function source files
      - --entry-point=helloWorld # Function entry point
      - tf-test-nc-demo-function # Function name
    waitFor: ['-'] # This step will wait until npm-test step complete.
    id: 'deploying-a-serverless-function'