steps:
 # Deploy the function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - --runtime=nodejs10
      - --trigger-http
      - --source=./  # Function source files
      - --entry-point=helloWorld # Function entry point
      - helloWorld # Function name
    waitFor: ['-'] # This step will wait until npm-test step complete.
    id: 'deploying-a-serverless-function'